[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Serve index.html for root path
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Handle 404s by serving index.html (for SPA-like behavior)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"